import {
  BarChart3,
  Boxes,
  Brain,
  Briefcase,
  Building2,
  CheckCircle2,
  Database,
  DollarSign,
  Eye,
  FileBarChart,
  FileText,
  FolderKanban,
  Landmark,
  Megaphone,
  MessageSquare,
  Scale,
  ShoppingCart,
  Users,
  UserCog,
} from "lucide-react";
import type { Layer } from "./types";

export const layers: Layer[] = [
  {
    color: "blue",
    icon: Landmark,
    eyebrow: "System of Record",
    system: "NetSuite ERP",
    message: "A single, accurate source of truth for every company transaction.",
    highlights: ["Finance", "Procurement", "Inventory", "Assets", "Reporting"],
    analogy: "Corporate Data Bank",
    analogyIcon: Database,
    panelTitle: "NetSuite ERP (System of Record)",
    panelSubtitle: "The core system that stores the company's official transaction data",
    footer: "Single Source of Truth — Accurate, Reliable, Auditable Data",
    items: [
      { icon: FileText, label: "General Ledger" },
      { icon: ShoppingCart, label: "Purchase Order" },
      { icon: UserCog, label: "Vendor Management" },
      { icon: Boxes, label: "Inventory Management" },
      { icon: Building2, label: "Asset Management" },
      { icon: DollarSign, label: "AP / AR Management" },
      { icon: FileBarChart, label: "Financial Statement" },
    ],
  },
  {
    color: "green",
    icon: Users,
    eyebrow: "System of Engagement",
    system: "Operations Platform",
    message: "Where employees work and run day-to-day business processes.",
    highlights: [
      "General Affairs",
      "Legal",
      "Compliance",
      "Marketing",
      "Budget Request",
      "Contract Management",
      "Approvals",
    ],
    analogy: "Operational Office",
    analogyIcon: Building2,
    scope: { label: "IT Dept" },
    panelTitle: "Enterprise Operations Platform (System of Engagement)",
    panelSubtitle: "The platform employees use to run everyday business processes",
    footer: "Employees Engage, Collaborate & Execute Everyday Processes",
    groups: [
      { icon: Megaphone, label: "Marketing", items: ["Campaign", "Event Request", "Campaign Approval"] },
      { icon: DollarSign, label: "Budget Request", items: ["Budget Request", "Budget Approval", "Tracking"] },
      { icon: Scale, label: "Legal", items: ["Contract Review", "Contract Renewal"] },
      { icon: CheckCircle2, label: "Compliance", items: ["Audit Finding", "Corrective Action", "Compliance Monitoring"] },
      { icon: Building2, label: "General Affairs", items: ["Asset Request", "Maintenance Request", "Vehicle Request"] },
      { icon: FolderKanban, label: "Workflow & Approval", items: ["Multi-Level Approval", "Task Management"] },
      { icon: FolderKanban, label: "Document Management", items: ["Document Repository", "Version Control", "Centralized"] },
      { icon: MessageSquare, label: "Notification & Collaboration", items: ["In-App Notification", "Collaboration", "Activity Feed"] },
    ],
  },
  {
    color: "purple",
    icon: Brain,
    eyebrow: "System of Intelligence",
    system: "Data Platform",
    message: "Turns data into insight for faster, sharper decisions.",
    highlights: [
      "Executive Dashboard",
      "Financial Dashboard",
      "HR Dashboard",
      "Operational & Ritel Dashboard",
      "GA Dashboard",
      "Compliance & Legal Dashboard",
      "Data Watchdog",
    ],
    analogy: "Corporate Brain",
    analogyIcon: Brain,
    scope: { label: "MRAMU", logoSrc: "/logos/mramu.png" },
    panelTitle: "Enterprise Data Platform (System of Intelligence)",
    panelSubtitle: "Dashboard & Analytics — turns data into insight for decision-making",
    footer: "Insight & Intelligence for Better Decision Making",
    items: [
      { icon: BarChart3, label: "Executive Dashboard [Leadership · Board]" },
      { icon: DollarSign, label: "Financial Dashboard [Finance · CFO]" },
      { icon: Users, label: "HR Dashboard [People · CHRO]" },
      { icon: Building2, label: "Operational & Ritel Dashboard [Operations · COO]" },
      { icon: Briefcase, label: "GA Dashboard [General Affairs]" },
      { icon: Scale, label: "Compliance & Legal Dashboard [Compliance · Legal · Audit]" },
      { icon: Eye, label: "Data Watchdog [Data Quality · Ops]" },
    ],
  },
];
